/*
 * app-manager
 *
 * App manager API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DownloadTypeQueryParam {
    #[serde(rename = "download_type")]
    pub download_type: crate::models::DownloadType,
}

impl DownloadTypeQueryParam {
    pub fn new(download_type: crate::models::DownloadType) -> DownloadTypeQueryParam {
        DownloadTypeQueryParam {
            download_type,
        }
    }
}


