/*
 * app-manager
 *
 * App manager API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SoftwareOptionsQueryParam {
    #[serde(rename = "software_options")]
    pub software_options: crate::models::SoftwareOptions,
}

impl SoftwareOptionsQueryParam {
    pub fn new(software_options: crate::models::SoftwareOptions) -> SoftwareOptionsQueryParam {
        SoftwareOptionsQueryParam {
            software_options,
        }
    }
}


