/*
 * app-manager
 *
 * App manager API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SoftwareOptions {
    #[serde(rename = "Manager")]
    Manager,
    #[serde(rename = "Backend")]
    Backend,

}

impl ToString for SoftwareOptions {
    fn to_string(&self) -> String {
        match self {
            Self::Manager => String::from("Manager"),
            Self::Backend => String::from("Backend"),
        }
    }
}

impl Default for SoftwareOptions {
    fn default() -> SoftwareOptions {
        Self::Manager
    }
}




