/*
 * app-manager
 *
 * App manager API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DownloadTypeQueryParam {
    #[serde(rename = "download_type")]
    pub download_type: models::DownloadType,
}

impl DownloadTypeQueryParam {
    pub fn new(download_type: models::DownloadType) -> DownloadTypeQueryParam {
        DownloadTypeQueryParam {
            download_type,
        }
    }
}

