/*
 * app-manager
 *
 * App manager API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DownloadType {
    #[serde(rename = "Info")]
    Info,
    #[serde(rename = "EncryptedBinary")]
    EncryptedBinary,

}

impl std::fmt::Display for DownloadType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Info => write!(f, "Info"),
            Self::EncryptedBinary => write!(f, "EncryptedBinary"),
        }
    }
}

impl Default for DownloadType {
    fn default() -> DownloadType {
        Self::Info
    }
}

