/*
 * app-manager
 *
 * App manager API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerNameText {
    #[serde(rename = "server")]
    pub server: String,
}

impl ServerNameText {
    pub fn new(server: String) -> ServerNameText {
        ServerNameText {
            server,
        }
    }
}

