/*
 * app-manager
 *
 * App manager API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SoftwareOptionsQueryParam {
    #[serde(rename = "software_options")]
    pub software_options: models::SoftwareOptions,
}

impl SoftwareOptionsQueryParam {
    pub fn new(software_options: models::SoftwareOptions) -> SoftwareOptionsQueryParam {
        SoftwareOptionsQueryParam {
            software_options,
        }
    }
}

