/*
 * app-manager
 *
 * App manager API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SoftwareInfo {
    #[serde(rename = "current_software")]
    pub current_software: Vec<models::BuildInfo>,
}

impl SoftwareInfo {
    pub fn new(current_software: Vec<models::BuildInfo>) -> SoftwareInfo {
        SoftwareInfo {
            current_software,
        }
    }
}

