/*
 * app-manager
 *
 * App manager API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemInfoList {
    #[serde(rename = "info")]
    pub info: Vec<models::SystemInfo>,
}

impl SystemInfoList {
    pub fn new(info: Vec<models::SystemInfo>) -> SystemInfoList {
        SystemInfoList {
            info,
        }
    }
}

