/*
 * app-manager
 *
 * App manager API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SystemInfoList {
    #[serde(rename = "info")]
    pub info: Vec<crate::models::SystemInfo>,
}

impl SystemInfoList {
    pub fn new(info: Vec<crate::models::SystemInfo>) -> SystemInfoList {
        SystemInfoList {
            info,
        }
    }
}


